name: Trigger auto deployment for samsara

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/samsara-AutoDeployTrigger-74b4e90d-9f49-4064-bd9a-3e860f9052c9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SAMSARA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SAMSARA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SAMSARA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SAMSARA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMSARA_REGISTRY_PASSWORD }}
          containerAppName: samsara
          resourceGroup: samsara-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


